### PR TITLE
Remove mapCoverage option

### PR DESCRIPTION
**Pull request by kimond**
The `mapCoverage` option is no longer used in the Jest configuration.

### CODE REVIEW

**Comment by kimond** [comment]
Oups I didn't notice that you were using jest < 22.4.

**Comment by eddyerburgh** [comment]
You could bump the Jest version too!

**Comment by kimond** [comment]
@eddyerburgh I bumped the jest version.

**Review by eddyerburgh — CHANGES_REQUESTED** [review]
Thanks, can you also remove the package-lock and add it to .gitignore?

**Comment by kimond** [comment]
Just to be sure, the package-lock is the `yarn.lock` right?

**Comment by kimond** [comment]
I removed the package-lock.json as you asked.

**Comment by LinusBorg** [comment]
As the examples is marked as outdated (see README), we're not gonna add new stuff/make changes.

**Pull request closed without merging**
